version: '3.9'

services:
  mysql:
    image: mysql:latest
    restart: always
    command: --innodb-use-native-aio=0
    container_name: mysqldb
    tty: true
    volumes:
      - mysqlvolume:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - proxyreverso
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 5s
      timeout: 10s
      retries: 4

  node:
    build:
      context: .
      dockerfile: Dockerfile.dev
    image: nodeapi
    container_name: nodeserver
    entrypoint: sh -c "npm install && npx prisma generate && npx prisma migrate deploy && npm run start"
    #command: bash -c "npm install && npx prisma generate && npx prisma migrate deploy && npm run start"
    volumes:
      - .:/usr/src/app
    tty: true
    networks:
      - proxyreverso
    depends_on:
      mysql:
        condition: service_healthy

  nginx:
      build:
        context: ./Nginx
        dockerfile: Dockerfile
      image: matheushenrique35/nginx-proxy-node
      container_name: nginxproxy
      networks:
        - proxyreverso
      ports:
        - "8089:80"
      depends_on:
        - mysql
        - node

networks:
  proxyreverso:
    driver: bridge

volumes:
  mysqlvolume:
    driver: local