FROM node:18-alpine3.20 

RUN apk add --no-cache bash

WORKDIR /usr/src/app

COPY package.json .

RUN npm i
# RUN npm ci
RUN npm install prisma
RUN npm install @prisma/client -g

COPY src/ .

RUN npx prisma generate

#apartir daqui a imagem pega o usuario node
USER node

EXPOSE 3000

CMD ["npm", "run",  "start"]