FROM node:18-alpine3.20 

RUN apk add --no-cache bash

WORKDIR /usr/src/app

COPY package.json .

RUN npm i
RUN npm install prisma
RUN npm install @prisma/client -g

COPY src/ .

RUN npx prisma generate

EXPOSE 3000

CMD ["npm", "run",  "start"]